apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  KC_DB: "postgres"
  KC_DB_URL: "jdbc:postgresql://pg-master:5432/keycloak?targetServerType=master"
  KC_DB_URL_REPLICA: "jdbc:postgresql://pg-slave:5432/keycloak?targetServerType=preferSlave"

  KC_FEATURES: "hostname:v2,multi-site"
  KC_HOSTNAME: "localhost"
  KC_HTTP_ENABLED: "true"
  KC_HEALTH_ENABLED: "true"
  KC_METRICS_ENABLED: "true"
  #KC_LOG_LEVEL: "DEBUG"

  KC_CACHE: "ispn"
  KC_CACHE_STACK: "kubernetes"
  KC_CACHE_REMOTE_HOST: "infinispan-cluster"
  KC_CACHE_REMOTE_PORT: "11222"
  KC_CACHE_REMOTE_USERNAME: "admin"
  KC_CACHE_REMOTE_PASSWORD: "superstrongpassword"
  KC_CACHE_REMOTE_TLS_ENABLED: "false"
  KC_CACHE_REMOTE_TIMEOUT: "10000"
