apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
spec:
  serviceName: "keycloak"
  replicas: 2
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: keycloak/keycloak:26.1
          imagePullPolicy: IfNotPresent
          args: [ "start" ]
          envFrom:
            - configMapRef:
                name: keycloak-config
            - secretRef:
                name: keycloak-db-secret
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: kc-data
              mountPath: /opt/keycloak/data
      restartPolicy: Always

  volumeClaimTemplates:
    - metadata:
        name: kc-data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 5Gi
