apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
spec:
  serviceName: "keycloak"
  replicas: 2
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: keycloak/keycloak:26.1
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              /opt/keycloak/bin/kc.sh build
              /opt/keycloak/bin/kc.sh start --optimized
          envFrom:
            - configMapRef:
                name: keycloak-config
            - secretRef:
                name: keycloak-db-secret
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: kc-data
              mountPath: /opt/keycloak/data

          securityContext:
            runAsUser: 1000
            runAsNonRoot: true

          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            httpGet:
              path: /health/live
              port: 8080

          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            httpGet:
              path: /health/ready
              port: 8080

          startupProbe:
            failureThreshold: 15 # 15*10 = 2.5m max wait time
            periodSeconds: 10
            httpGet:
              path: /health/ready
              port: 8080

          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 1000m
              memory: 5Gi

  volumeClaimTemplates:
    - metadata:
        name: kc-data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 5Gi
