apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
type: Opaque
data:
  KC_DB_USERNAME: cG9zdGdyZXM=
  KC_DB_PASSWORD: cGFzc3dvcmQ=
  KC_BOOTSTRAP_ADMIN_USERNAME: YWRtaW4=
  KC_BOOTSTRAP_ADMIN_PASSWORD: c3VwZXJzdHJvbmdwYXNzd29yZA==
