apiVersion: v1
kind: Secret
metadata:
  name: kc-secret
type: Opaque
data:
  KC_DB_USERNAME: "cG9zdGdyZXM=" # postgres
  KC_DB_PASSWORD: "c3VwZXJzdHJvbmdwYXNzd29yZA==" # superstrongpassword

  KC_BOOTSTRAP_ADMIN_USERNAME: "YWRtaW4=" # admin
  KC_BOOTSTRAP_ADMIN_PASSWORD: "c3VwZXJzdHJvbmdwYXNzd29yZA=="
