apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: https
      port: 8443
      targetPort: https
    - name: cli
      port: 9000
      targetPort: cli
  type: ClusterIP
  selector:
    app: keycloak
