apiVersion: "acid.zalan.do/v1"
kind: postgresql

metadata:
  name: min
  labels:
    application: min-cl

spec:
  teamId: "acid"
  numberOfInstances: 2

  enableLogicalBackup: true
  enableMasterLoadBalancer: true
  enableReplicaLoadBalancer: true
  enableConnectionPooler: true # enable/disable connection pooler deployment
  enableReplicaConnectionPooler: false
  enableMasterPoolerLoadBalancer: false
  enableReplicaPoolerLoadBalancer: false
  allowedSourceRanges: # load balancers' source ranges for both master and replica services
    - 127.0.0.1/32

  postgresql:
    version: "17"
    parameters:
      shared_buffers: "1GB"
      max_connections: "200"
      work_mem: "32MB"
      log_statement: "all"
      password_encryption: "scram-sha-256"

  users:
    postgres:
      - superuser
      - createdb
    app_owner: []

  databases:
    app_db: app_owner  # dbname: owner
  preparedDatabases:
    app_db:
      schemas:
        public: {}

  volume:
    size: 100Gi

  resources:
    requests:
      cpu: 300m
      memory: 400Mi
#      hugepages-2Mi: 128Mi
#      hugepages-1Gi: 1Gi
    limits:
      cpu: 500m
      memory: 500Mi
#      hugepages-2Mi: 128Mi
#      hugepages-1Gi: 1Gi

  patroni:
    failsafe_mode: false
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    synchronous_mode: false
    synchronous_mode_strict: false
    synchronous_node_count: 1
    maximum_lag_on_failover: 33554432
    initdb:
      encoding: "UTF8"
      locale: "en_US.UTF-8"
      data-checksums: "true"

  maintenanceWindows:
  - 01:00-06:00
