apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: infinispan
spec:
  serviceName: "infinispan"
  replicas: 2
  selector:
    matchLabels:
      app: infinispan
  template:
    metadata:
      labels:
        app: infinispan
    spec:
      containers:
        - name: infinispan
          image: quay.io/infinispan/server:15.1
          ports:
            - name: ispn
              containerPort: 11222
            - name: jgroups
              containerPort: 7800
            - name: jmx
              containerPort: 57800
          envFrom:
            - configMapRef:
                name: ispn-config
          volumeMounts:
            - name: ispn-data
              mountPath: /opt/infinispan/data
            - name: ispn-config
              mountPath: /opt/infinispan/server/conf/infinispan.xml
              subPath: infinispan.xml
      volumes:
        - name: ispn-config
          configMap:
            name: ispn-config
            items:
              - key: infinispan.xml
                path: infinispan.xml
  volumeClaimTemplates:
    - metadata:
        name: ispn-data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 5Gi
