apiVersion: v1
kind: ConfigMap
metadata:
  name: ispn-config
data:
  USER: "admin"
  PASS: "superstrongpassword"

  INFINISPAN_HTTP_PORT: "11222"
  INFINISPAN_CLUSTER_NAME: "infinispan-cluster"

  INFINISPAN_JGROUPS_DISCOVERY_PROTOCOL: "DNS_PING"
  INFINISPAN_JGROUPS_DNS_QUERY: "infinispan-cluster.default.svc.cluster.local"
