apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: infinispan
spec:
  serviceName: "infinispan"
  replicas: 2
  selector:
    matchLabels:
      app: infinispan
  template:
    metadata:
      labels:
        app: infinispan
    spec:
      containers:
        - name: infinispan
          image: jboss/infinispan-server:10.1
          ports:
            - containerPort: 11222
            - containerPort: 7800
          envFrom:
            - configMapRef:
                name: ispn-config
          volumeMounts:
            - name: infinispan-data
              mountPath: /opt/infinispan/data
  volumeClaimTemplates:
    - metadata:
        name: infinispan-data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 1Gi