apiVersion: v1
kind: Service
metadata:
  name: infinispan-cluster
spec:
  ports:
    - name: ispn
      port: 11222
      targetPort: ispn
    - name: jgroups
      port: 7800
      targetPort: jgroups
    - name: jmx
      port: 57800
      targetPort: jmx
  clusterIP: None
  selector:
    app: infinispan
