apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: "minio/minio:RELEASE.2025-02-07T23-21-09Z-cpuv1"
          args:
            - server
            - /data
            - --console-address
            - ":9001"

          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    until mc alias set minio http://localhost:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD; do
                      echo "Waiting for MinIO to be ready..."
                      sleep 5
                    done
                    mc mb minio/postgres-backups || true
                    mc mb minio/cluster-common || true

          envFrom:
            - secretRef:
                name: minio-secret

          ports:
            - name: srv
              containerPort: 9000
            - name: cli
              containerPort: 9001
          volumeMounts:
            - name: minio-data
              mountPath: /data

          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            httpGet:
              path: /minio/health/live
              port: 9000

          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            httpGet:
              path: /minio/health/live
              port: 9000

      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-pvc
