apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-slave-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: pg-slave-pv