apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg-slave
spec:
  serviceName: pg-slave
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      role: slave
  template:
    metadata:
      labels:
        app: postgres
        role: slave
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: postgres
          image: postgres:15
          envFrom:
            - configMapRef:
                name: slave-config
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
          command:
            - bash
            - -c
            - |
              # Extract replica name from the pod's hostname (e.g., pg-slave-0)
              REPLICA_NAME=$(hostname | sed 's/-/_/g')
              
              rm -rf /var/lib/postgresql/data/*
              until pg_isready --host=pg-master --port=5432; do
                echo "Waiting for master to be ready…"
                sleep 2
              done
              
              pg_basebackup --host pg-master --pgdata /tmp/pgdata --username postgres --verbose --progress --wal-method=stream
              mv /tmp/pgdata/* /var/lib/postgresql/data/
              chown -R postgres:postgres /var/lib/postgresql/data/
              
              psql --host pg-master --username postgres -tc "SELECT 1 FROM pg_replication_slots WHERE slot_name = '${REPLICA_NAME}'" | grep -q 1 || \
              psql --host pg-master --username postgres -c "SELECT pg_create_physical_replication_slot('${REPLICA_NAME}');"
            
              echo "primary_slot_name = '${REPLICA_NAME}'" | tee -a /var/lib/postgresql/data/postgresql.conf
              echo "primary_conninfo = 'host=pg-master port=5432 user=postgres password=password application_name=${REPLICA_NAME}'" | tee -a /var/lib/postgresql/data/postgresql.conf
              
              touch /var/lib/postgresql/data/standby.signal
              chmod 700 /var/lib/postgresql/data/
              
              rm -rf /tmp/pgdata
              echo "Starting PostgreSQL…"
              postgres
      volumes:
        - name: pg-data
          persistentVolumeClaim:
            claimName: pg-slave-pvc