apiVersion: v1
kind: Service
metadata:
  name: pg-slave
spec:
  type: NodePort
  selector:
    app: postgres
    role: slave
  ports:
    - protocol: TCP
      port: 5432
      nodePort: 30002