apiVersion: v1
kind: ConfigMap
metadata:
  name: master-config
data:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
  POSTGRES_HOST: "pg-master"
  POSTGRES_PORT: "5432"
  PGDATA: "/var/lib/postgresql/data"

  pg_hba.conf: |
    local   all             all                                     trust
    host    all             all             127.0.0.1/32            trust
    host    all             all             ::1/128                 trust
    host    replication     all             0.0.0.0/0               scram-sha-256
    host    all             all             0.0.0.0/0               md5

  postgresql.conf: |
    listen_addresses = '*'
    wal_level = replica
    max_wal_senders = 10
    max_replication_slots = 10
    wal_keep_size = 64
