apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-master-pv
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pgsql/kube/master