apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-master-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: pg-master-pv