apiVersion: v1
kind: Service
metadata:
  name: pg-master
spec:
  type: NodePort
  selector:
    app: postgres
    role: master
  ports:
    - protocol: TCP
      port: 5432
      nodePort: 30001 # Assign a specific port (optional)