apiVersion: v1
kind: ConfigMap
metadata:
  name: slave-config
data:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
  PGPASSWORD: "password"
  POSTGRES_HOST: "pg-slave"
  POSTGRES_PORT: "5432"
  PGDATA: "/var/lib/postgresql/data"